version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    formats: ["tar.gz"]
    files:
      - README.md

dockers:
  - image_templates:
      - "ghcr.io/skidoodle/safebin:{{ .Version }}-amd64"
      - "ghcr.io/skidoodle/safebin:latest-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

  - image_templates:
      - "ghcr.io/skidoodle/safebin:{{ .Version }}-arm64"
      - "ghcr.io/skidoodle/safebin:latest-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

docker_manifests:
  - name_template: "ghcr.io/skidoodle/safebin:{{ .Version }}"
    image_templates:
      - "ghcr.io/skidoodle/safebin:{{ .Version }}-amd64"
      - "ghcr.io/skidoodle/safebin:{{ .Version }}-arm64"
  - name_template: "ghcr.io/skidoodle/safebin:latest"
    image_templates:
      - "ghcr.io/skidoodle/safebin:latest-amd64"
      - "ghcr.io/skidoodle/safebin:latest-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
